Issue/51 global comments
MIDA-group/CytoBrowser pull request #133
Opened 2021-07-15 01:26 UTC by crydell

Added the ability to add global comments to a session, which are also stored persistently. Includes QoL features like pressing `Esc` to unfocus the comment field and `Enter` to submit a comment without pressing the "Add Comment" button.

Since the comments themselves are very similar to the comments that can be made on individual annotations, I initially tried to use the same code for both pieces of functionality, but I ended up scrapping this due to the communication with the server working too differently between the two. Since the current idea of CytoBrowser always requires a user to be connected to a session when working, I think it may be relevant to change how annotations are added (user says where annotation should go -> server broadcasts where the annotation is with an ID) in order to simplify the code at some point, which would make this shared comment section code easier to sort out.

2021-07-15 21:58 UTC, joakimlindblad reviewed
It's a good start. I had on mind more of a freetext area, but this fits in deed nicely with the annotation comments.
In the future one would want edit and reorder options, but all in due time.

Some minor comments: 
1. I prefer the full width rendering (of short comments) as in the context menu.
2. With enter="add comment", shift-enter (as we have learnt from glip/slack/whatsapp etc.) works well for adding a new line in the writing field, but is not honoured in the comment view.
3. It has very space taking margins, do shrink them a bit.
4. Future work would include (i) some indicator (counter) on the closed/folded button; (ii) allow resizing of fields (input and view)

**Note:** (just to not mix concepts in metadataHandler and annotationHandler)
Image Metadata (such as pixelsize etc) are read only and associated with the *image*
Global comments are also annotations, and associated with the *session*

2021-07-15 22:06 UTC, joakimlindblad requested changes
When you merge, do it into **develop** (seems you will need to do some interactive rebasing)

2021-07-16 14:06 UTC, crydell commented
I took care of changes 1-3, and 4 seems like it should be rather simple to implement so I will give it a look during the weekend.

I noticed another bug while testing, which may or may not be important right now depending on the current users. Some languages, e.g. various Chinese languages, use [input methods](https://support.microsoft.com/en-us/windows/microsoft-traditional-chinese-ime-ef596ca5-aff7-4272-b34b-0ac7c2631a38) where the user first types in a phonetic reading of a character, then selects the correct character in a list, and then presses `Enter` to input the character. When doing this in the current version, it inputs the character and immediately submits the comment. Depending on the priority of non-English usage of the tool, I could either look into fixing this soon or leave it for later.

2021-07-20 21:39 UTC, joakimlindblad commented
Points 1-3 seem well addressed (I tightened the margins a bit further).
Observe my note about naming convention about "metadata" vs global annotation comments above; do rename files/methods if names are misleading (better sooner than later).
Merge (with develop) when you see fit (though I still believe point 4 is nice to have).

2021-07-25 13:12 UTC, merged