Issue/169 self intersect
MIDA-group/CytoBrowser pull request #181
Opened 2021-12-14 23:50 UTC by crydell

Pull request for issue #169 . The prevention of self-intersection is done in `annotationTool`, and uses logic from `mathUtils`. It may be relevant to move more general math functions to `mathUtils` at some point, e.g. `getCentroid()`. Note when testing that there may be situations where it may look like there is an intersection, e.g. clicking [(0,0), (1, 0), (0, 1), (1, 1)], but the intersection here only comes from the current hypothetical closing segment; it is not possible to complete the region without adding more vertices that make it non-intersecting, as seen in this image:
![bild](https://user-images.githubusercontent.com/31703366/146097244-ac3ea953-f5c2-4827-8c8e-7c8ffd578cc2.png)

2022-01-01 18:55 UTC, joakimlindblad commented
1. Seems to work :-)
2. Would not mind brief descriptions of the individual functions, instead of (in addition to) "Functions below..."
3. **But**, we can still create self intersecting polygons in "Region editing mode" (thus screwing up centroid comput.)
4. I think it would be nice with some visual drawing feedback (not easy to pick what, change of interior fill to striped perhaps)
5. Yes, I agree that over time we may move more stuff to mathUtils

2022-01-01 18:56 UTC, joakimlindblad requested changes
See comments in conversation

2022-01-17 22:18 UTC, crydell commented
> See comments in conversation

I amended comments 2 and 3, I think 4 might be better for a separate issue.

2022-01-17 22:42 UTC, merged

2022-01-17 22:50 UTC, joakimlindblad commented
I agree. Opening new issue #193.

Also, the detachment of the mouse cursor and the polygon vertex point when going non-convex, and then dragging back is non-ideal; but it's the same which happens if dragging a point outside of the image, and then back. Will make a 2nd issue of that, #194. For future days.